# Generated by Django 5.0.1 on 2024-01-15 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='clase',
            name='duracion',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.clase', verbose_name='Clase'),
        ),
    ]
